# Generated by Django 3.0.5 on 2020-04-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=30)),
                ('restro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.RestaurantModel')),
            ],
        ),
    ]
