# Generated by Django 3.0.5 on 2020-04-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20200416_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
