# Generated by Django 2.2.5 on 2020-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('food_no', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
